"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['game.py']
DATA_FILES = [ ('', ["images"]), ('', ["sounds"]) ]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'icon.icns',
    'plist': {
        'CFBundleName': "Balloon Pop",
        'CFBundleDisplayName': "Balloon Pop",
        'CFBundleGetInfoString': "Balloon pop app in Python",
        'CFBundleIdentifier': "com.mwsywensky.osx.balloonpop",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"MIT"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
